name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'
          rtools-version: ''
          cran: 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/'
      - run: |
          Rscript -e 'Sys.setenv(GITHUB_PAT="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")'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::ggplot2
            any::limma
            any::gert
            any::devtools
            any::Seurat
            any::h5mread
            any::HDF5Array
            any::glmGamPoi
            any::GenomeInfoDb
            any::Rsamtools
            any::Signac
            any::R.utils
            any::SoupX
            any::scDblFinder
          upgrade: 'TRUE'
          needs: check
      - run: |
          Rscript -e 'devtools::install_github("satijalab/seurat-data")'
          Rscript -e 'install.packages('BPCells', repos=c('https://bnprks.r-universe.dev', 'https://cloud.r-project.org'))'
          Rscript -e 'install.packages('presto', repos=c('https://satijalab.r-universe.dev', 'https://cloud.r-project.org'))'
          Rscript -e 'devtools::install_github("satijalab/azimuth")'
          Rscript -e 'devtools::install_github("satijalab/seurat-wrappers")'
          Rscript -e 'devtools::install_github('chris-mcginnis-ucsf/DoubletFinder')'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          pip install mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-git-authors-plugin
          pip install mkdocs-git-committers-plugin-2
          pip install mkdocs-glightbox
          pip install mkdocs-jupyter
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install torch_geometric
          pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.8.0+cpu.html
          pip install scikit-image
          pip install pymde
          pip install scvi-tools
          pip install louvain
          pip install rpy2
          pip install anndata2ri
          pip install kneed
          pip install rapids_singlecell
          pip install celltypist
          pip install torchdr
          pip install intervaltree fbpca annoy
          pip install patchworklib
          pip install omicverse
          pip install jupyterlab

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: mkdocs gh-deploy --force