name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'
          rtools-version: ''
          cran: 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/'

      - name: Create and configure user library
        run: |
            # 创建用户库目录
            mkdir -p ~/R/library
            mkdir -p ~/.R
            
            # 创建 R 配置文件
            cat > ~/.Rprofile << 'EOF'
            # 设置用户库路径
            .libPaths(c("~/R/library", .libPaths()))
            # 设置选项
            options(BioC_mirror='https://mirrors.tuna.tsinghua.edu.cn/bioconductor/')
            EOF

      - name: Set R library path
        run: |
          echo "R_LIBS_USER=~/R/library" >> $GITHUB_ENV
          echo "R_LIBS=~/R/library" >> $GITHUB_ENV

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::ggplot2
            any::BiocManager
            any::devtools
          upgrade: 'TRUE'
          needs: check

      - name: Install R packages
        run: |
          Rscript -e "
          Sys.setenv(GITHUB_PAT='${{ secrets.GITHUB_TOKEN }}')
          
          BiocManager::install(version='3.22')
          BiocManager::install('limma')
          
          install.packages('Seurat')
          BiocManager::install('h5mread')
          BiocManager::install('HDF5Array')
          BiocManager::install('glmGamPoi')
          install.packages('BPCells', repos=c('https://bnprks.r-universe.dev', 'https://cloud.r-project.org'))
          install.packages('presto', repos=c('https://satijalab.r-universe.dev', 'https://cloud.r-project.org'))
          BiocManager::install('GenomeInfoDb')
          BiocManager::install('Rsamtools')
          install.packages('Signac')
          devtools::install_github('satijalab/seurat-data', auth_token=Sys.getenv('GITHUB_PAT'))
          devtools::install_github('satijalab/azimuth', auth_token=Sys.getenv('GITHUB_PAT'))
          install.packages('R.utils')
          devtools::install_github('satijalab/seurat-wrappers', auth_token=Sys.getenv('GITHUB_PAT'))
          install.packages('SoupX')
          BiocManager::install('plger/scDblFinder')
          devtools::install_github('chris-mcginnis-ucsf/DoubletFinder', auth_token=Sys.getenv('GITHUB_PAT'))
          "

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python packages
        run: |
          pip install mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-git-authors-plugin
          pip install mkdocs-git-committers-plugin-2
          pip install mkdocs-glightbox
          pip install mkdocs-jupyter
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install torch_geometric
          pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.8.0+cpu.html
          pip install scikit-image
          pip install pymde
          pip install scvi-tools
          pip install louvain
          pip install rpy2
          pip install anndata2ri
          pip install kneed
          pip install rapids_singlecell
          pip install celltypist
          pip install torchdr
          pip install intervaltree fbpca annoy
          pip install patchworklib
          pip install omicverse
          pip install jupyterlab

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: |
            mkdocs-material-${{ env.cache_id }}
            ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}-${{ hashFiles('**/renv.lock') }}
          path: |
            .cache
            ~/R/library
          restore-keys: |
            mkdocs-material-
            ${{ runner.os }}-r-

      - run: mkdocs gh-deploy --force